# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!


source 'git@192.168.1.78:zhangkaichao/ALSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'YiDing' do

#pod 'ALNetwork', '~> 0.0.7'
pod 'AFNetworking', '~> 3.1.0'
pod 'FMDB', '~> 2.5'
pod 'YYModel', '~> 0.9.11'
pod 'Masonry', '~> 0.6.4'
pod 'MJRefresh', '~> 3.1.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'Qiniu', '~> 7.1.0.1'
pod 'ShareSDK3' , '~> 3.3.1'
pod 'MOBFoundation', '~> 1.5.3'
pod 'ShareSDK3/ShareSDKUI', '~> 3.3.1'
pod 'ShareSDK3/ShareSDKPlatforms/QQ' , '~> 3.3.1'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo' , '~> 3.3.1'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat' , '~> 3.3.1'
pod 'UMengAnalytics-NO-IDFA', '~> 4.0.3'
#pod 'BrandcastSDK', '~> 0.0.6'
pod 'SSKeychain', '~> 1.4.0'
pod 'JSONKit-NoWarning', '~> 1.2'
pod 'JDStatusBarNotification', '~> 1.5.3'
pod 'ALPDFPPTReader', '~> 0.1.6'
pod 'hpple', '~> 0.2.0'
pod 'YYText', '~> 1.0.5'
pod 'ALStatistics', '~> 0.1.3'
pod 'ALSVGKit', '~> 2.0.0.2'

pod 'Base64', '~> 1.1.2'
pod 'Aspects', '~> 1.4.1'
pod 'WebViewJavascriptBridge', '~> 5.0.5'
pod 'MJExtension', '~> 3.0.13'
pod 'HandyAutoLayout', '~> 1.0.0'

end

